### ISSUE TITLE
Prevent Actions to run more than once per software version

### ISSUE THREAD

**Issue by nvk** [coinkite/bitcoinbinary.org#34]
@kdunn926 As per title, we need to prevent the action from running again over the same project version.

**Comment by kdunn926** [comment]
This is expected given that no artifacts were generated. As long as at least one project has an updated artifact the workflow will be all green and this error won't occur.

**Comment by nvk** [comment]
I guess there is no cleaner way of retuning a a better response to “nothing to build”

closing the issues.
