### ISSUE TITLE
GH Actions not seeing Coldcard's new version.

### ISSUE THREAD

**Issue by nvk** [coinkite/bitcoinbinary.org#36]

**Comment by nvk** [comment]
cc @kdunn926

**Comment by kdunn926** [comment]
Make sure to update both `VERSION` and (if it exists) `VERSION_STRING` to match the desired tag in the project needing a new build video. This update needs to happen in both `steps.sh` and `artifacts.sh`.

The version updates need to be done manually (via commit/PR) unless someone can come up with a simple/maintainable way of handling all the variations of release tags across the existing projects (and future projects).
